### ISSUE TITLE
Progress filtering by raid size

### ISSUE THREAD

**Issue by query-wow** [tauriprogress/server#1]
Currently when you filter via raid size, it doesn't take into the account the actual kill date of the filtered raid size mode. It takes the first date of the kill no matter what raid size it is. 
How to reproduce

Filter 25 heroic in evermoon
You'll find Kawaii Pandas in first place, even tho Muzykanci z Gruzji has the first kill in 25 heroic

KP's first 25 heroic kill date
![image](https://user-images.githubusercontent.com/660776/79028633-c0e19780-7b88-11ea-9345-dc861c0614bb.png)

MZG's first 25 heroic kill Date
![image](https://user-images.githubusercontent.com/660776/79028617-aad3d700-7b88-11ea-87e0-d6817c1165a0.png)

**Comment by akoskoc** [comment]
Thanks for the report, sorry for the late response. Fixed it in the other repo. https://github.com/tauriprogress/tauriprogress.github.io/commit/bd815780a79873e2cc2af680d1e137afbc237158
